"""Update log schema

Revision ID: 4b7c4bc23142
Revises: 74d2f878938f
Create Date: 2026-06-02 20:33:01.617848

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b7c4bc23142'
down_revision: str | Sequence[str] | None = '74d2f878938f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:

        batch_op.drop_column('deleted_at')
        batch_op.drop_column('datetime')
        batch_op.drop_column('active')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
