"""replace_auto_add_list_id_with_n_n_relation

Revision ID: 6766aaf838e9
Revises: e8567fb0573a
Create Date: 2026-06-05 18:59:41.196691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6766aaf838e9'
down_revision: Union[str, Sequence[str], None] = 'e8567fb0573a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_setting_tag_list_links',
    sa.Column('group_setting_id', sa.Uuid(), nullable=False),
    sa.Column('tag_list_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_setting_id'], ['group_settings.id'], ),
    sa.ForeignKeyConstraint(['tag_list_id'], ['tag_lists.id'], ),
    sa.PrimaryKeyConstraint('group_setting_id', 'tag_list_id')
    )
    with op.batch_alter_table('group_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('group_settings_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('auto_add_list_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_add_list_id', mysql.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f('group_settings_ibfk_1'), 'tag_lists', ['auto_add_list_id'], ['id'])

    op.drop_table('group_setting_tag_list_links')
    # ### end Alembic commands ###
