"""initial_schema

Revision ID: 6c5fe1fb7702
Revises: 
Create Date: 2026-05-31 17:58:45.978049

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c5fe1fb7702'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_groups')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('group_members',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_groups_group_id'), ['group_id'])

    with op.batch_alter_table('groups_users', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('datetime',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('datetime',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_user_id'), type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])
        batch_op.alter_column('datetime',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('groups_users', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_groups_group_id'), type_='unique')
        batch_op.alter_column('group_members',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('group_name', sa.TEXT(), nullable=True),
    sa.Column('group_description', sa.TEXT(), nullable=True),
    sa.Column('group_username', sa.TEXT(), nullable=True),
    sa.Column('group_type', sa.TEXT(), nullable=True),
    sa.Column('group_members', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    # ### end Alembic commands ###
