"""refactor_list_system

Revision ID: 74d2f878938f
Revises: 6c5fe1fb7702
Create Date: 2026-06-02 19:56:24.795685

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74d2f878938f"
down_revision: str | Sequence[str] | None = "6c5fe1fb7702"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_admin_exclusions",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag_lists",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trigger_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "list_users",
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["tag_lists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Custom Data Migration
    connection = op.get_bind()
    import json

    # 1. Fetch all unique group_ids from groups_users
    groups_users_records = connection.execute(
        sa.text("SELECT id, group_id, user_id FROM groups_users")
    ).fetchall()

    if groups_users_records:
        group_ids = set(row[1] for row in groups_users_records if row[1] is not None)

        for group_id in group_ids:
            # Create a default "everyone" list for this group
            result = connection.execute(
                sa.text(
                    "INSERT INTO tag_lists (group_id, name, trigger_name, is_system, aliases, active) "
                    "VALUES (:group_id, 'Everyone', 'everyone', 1, :aliases, 1)"
                ),
                {"group_id": group_id, "aliases": json.dumps(["all"])},
            )
            list_id = result.lastrowid

            # Fetch users for this group and insert into list_users
            users_in_group = [
                row[2]
                for row in groups_users_records
                if row[1] == group_id and row[2] is not None
            ]
            for user_id in users_in_group:
                connection.execute(
                    sa.text(
                        "INSERT INTO list_users (list_id, user_id, active) "
                        "VALUES (:list_id, :user_id, 1)"
                    ),
                    {"list_id": list_id, "user_id": user_id},
                )

    op.drop_table("_alembic_tmp_groups")
    op.drop_table("groups_users")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "active", sa.Boolean(), server_default=sa.text("1"), nullable=False
            )
        )
        batch_op.alter_column(
            "group_name",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_description",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_username",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_type",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )

    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "active", sa.Boolean(), server_default=sa.text("1"), nullable=False
            )
        )
        batch_op.alter_column(
            "action",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "datetime",
            existing_type=sa.TEXT(),
            type_=sa.DateTime(timezone=True),
            nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "active", sa.Boolean(), server_default=sa.text("1"), nullable=False
            )
        )
        batch_op.alter_column(
            "first_name",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "last_name",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TEXT(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TEXT(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "username",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "last_name",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "first_name",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("active")
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "groups", ["group_id"], ["group_id"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["user_id"])
        batch_op.alter_column(
            "datetime",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TEXT(),
            nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "action",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=False,
        )
        batch_op.drop_column("active")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.alter_column(
            "group_type",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_username",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_name",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("active")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    op.create_table(
        "groups_users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("group_id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("datetime", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "_alembic_tmp_groups",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("group_id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("group_name", sa.TEXT(), nullable=True),
        sa.Column("group_description", sa.TEXT(), nullable=True),
        sa.Column("group_username", sa.TEXT(), nullable=True),
        sa.Column("group_type", sa.TEXT(), nullable=True),
        sa.Column("group_members", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", name=op.f("uq_groups_group_id")),
    )
    op.drop_table("list_users")
    op.drop_table("tag_lists")
    op.drop_table("group_admin_exclusions")
    # ### end Alembic commands ###
