"""add group setting

Revision ID: 9d65b5e45798
Revises: 78b8cbd18cf5
Create Date: 2026-06-05 18:23:25.181966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d65b5e45798'
down_revision: Union[str, Sequence[str], None] = '78b8cbd18cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_settings',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('auto_add_new_members', sa.Boolean(), nullable=False),
    sa.Column('auto_add_list_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auto_add_list_id'], ['tag_lists.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_settings')
    # ### end Alembic commands ###
