"""rename_group_id_to_telegram_id

Revision ID: a275eac6c2a0
Revises: d41c263cd9e8
Create Date: 2026-06-02 21:13:41.712201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a275eac6c2a0'
down_revision: Union[str, Sequence[str], None] = 'd41c263cd9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('group_id', new_column_name='telegram_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
