"""fk_updates

Revision ID: d41c263cd9e8
Revises: eb574da9e153
Create Date: 2026-06-02 21:11:56.602103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd41c263cd9e8'
down_revision: Union[str, Sequence[str], None] = 'eb574da9e153'
branch_labels: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # Data Migration: Map Telegram group_id to internal group id
    op.execute("DELETE FROM tag_lists WHERE NOT EXISTS (SELECT 1 FROM groups WHERE groups.group_id = tag_lists.group_id)")
    op.execute("DELETE FROM logs WHERE group_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM groups WHERE groups.group_id = logs.group_id)")
    op.execute("DELETE FROM group_admin_exclusions WHERE NOT EXISTS (SELECT 1 FROM groups WHERE groups.group_id = group_admin_exclusions.group_id)")

    op.execute("UPDATE tag_lists SET group_id = (SELECT id FROM groups WHERE groups.group_id = tag_lists.group_id)")
    op.execute("UPDATE logs SET group_id = (SELECT id FROM groups WHERE groups.group_id = logs.group_id) WHERE group_id IS NOT NULL")
    op.execute("UPDATE group_admin_exclusions SET group_id = (SELECT id FROM groups WHERE groups.group_id = group_admin_exclusions.group_id)")

    # Recreate tag_lists
    op.execute("""
    CREATE TABLE tag_lists_new (
        group_id INTEGER NOT NULL,
        name VARCHAR NOT NULL,
        description VARCHAR,
        trigger_name VARCHAR NOT NULL,
        is_system BOOLEAN NOT NULL,
        aliases JSON,
        id INTEGER NOT NULL,
        created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
        updated_at DATETIME,
        deleted_at DATETIME,
        active BOOLEAN NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(group_id) REFERENCES groups (id)
    )
    """)
    op.execute("INSERT INTO tag_lists_new SELECT * FROM tag_lists")
    op.execute("DROP TABLE tag_lists")
    op.execute("ALTER TABLE tag_lists_new RENAME TO tag_lists")

    # Recreate logs
    op.execute("""
    CREATE TABLE logs_new (
        id INTEGER NOT NULL,
        user_id INTEGER,
        group_id INTEGER,
        action VARCHAR,
        description VARCHAR,
        created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(user_id) REFERENCES users (user_id),
        FOREIGN KEY(group_id) REFERENCES groups (id)
    )
    """)
    op.execute("INSERT INTO logs_new SELECT * FROM logs")
    op.execute("DROP TABLE logs")
    op.execute("ALTER TABLE logs_new RENAME TO logs")

    # Recreate group_admin_exclusions
    op.execute("""
    CREATE TABLE group_admin_exclusions_new (
        group_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        reason VARCHAR,
        id INTEGER NOT NULL,
        created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
        updated_at DATETIME,
        deleted_at DATETIME,
        active BOOLEAN NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(user_id) REFERENCES users (user_id),
        FOREIGN KEY(group_id) REFERENCES groups (id)
    )
    """)
    op.execute("INSERT INTO group_admin_exclusions_new SELECT * FROM group_admin_exclusions")
    op.execute("DROP TABLE group_admin_exclusions")
    op.execute("ALTER TABLE group_admin_exclusions_new RENAME TO group_admin_exclusions")


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_lists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('group_admin_exclusions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])

    # ### end Alembic commands ###
