"""Add active and deleted_at to GroupSetting

Revision ID: e8567fb0573a
Revises: 9d65b5e45798
Create Date: 2026-06-05 18:47:37.543837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8567fb0573a'
down_revision: Union[str, Sequence[str], None] = '9d65b5e45798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_settings', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
