// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PublicApiCreateListData, PublicApiCreateListErrors, PublicApiCreateListResponses, PublicApiDeleteListData, PublicApiDeleteListErrors, PublicApiDeleteListResponses, PublicApiGetAdminLogsData, PublicApiGetAdminLogsErrors, PublicApiGetAdminLogsResponses, PublicApiGetListsData, PublicApiGetListsErrors, PublicApiGetListsResponses, PublicApiGetUserGroupsData, PublicApiGetUserGroupsErrors, PublicApiGetUserGroupsResponses, PublicApiLoginTglData, PublicApiLoginTglErrors, PublicApiLoginTglResponses, PublicApiLoginTmaData, PublicApiLoginTmaErrors, PublicApiLoginTmaResponses, PublicApiSubscribeToListData, PublicApiSubscribeToListErrors, PublicApiSubscribeToListResponses, PublicApiUnsubscribeFromListData, PublicApiUnsubscribeFromListErrors, PublicApiUnsubscribeFromListResponses, PublicApiUpdateListData, PublicApiUpdateListErrors, PublicApiUpdateListResponses, SystemSystemStatusData, SystemSystemStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get groups for the current user
 */
export const publicApiGetUserGroups = <ThrowOnError extends boolean = false>(options?: Options<PublicApiGetUserGroupsData, ThrowOnError>) => (options?.client ?? client).get<PublicApiGetUserGroupsResponses, PublicApiGetUserGroupsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups',
    ...options
});

/**
 * Get weekly logs (Admin only)
 */
export const publicApiGetAdminLogs = <ThrowOnError extends boolean = false>(options?: Options<PublicApiGetAdminLogsData, ThrowOnError>) => (options?.client ?? client).get<PublicApiGetAdminLogsResponses, PublicApiGetAdminLogsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/admin/logs',
    ...options
});

/**
 * Login Tma
 */
export const publicApiLoginTma = <ThrowOnError extends boolean = false>(options: Options<PublicApiLoginTmaData, ThrowOnError>) => (options.client ?? client).post<PublicApiLoginTmaResponses, PublicApiLoginTmaErrors, ThrowOnError>({
    url: '/api/v1/public/auth/telegram-tma',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login Tgl
 */
export const publicApiLoginTgl = <ThrowOnError extends boolean = false>(options: Options<PublicApiLoginTglData, ThrowOnError>) => (options.client ?? client).post<PublicApiLoginTglResponses, PublicApiLoginTglErrors, ThrowOnError>({
    url: '/api/v1/public/auth/telegram-tgl',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all lists for a group
 */
export const publicApiGetLists = <ThrowOnError extends boolean = false>(options: Options<PublicApiGetListsData, ThrowOnError>) => (options.client ?? client).get<PublicApiGetListsResponses, PublicApiGetListsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/lists',
    ...options
});

/**
 * Create a new list
 */
export const publicApiCreateList = <ThrowOnError extends boolean = false>(options: Options<PublicApiCreateListData, ThrowOnError>) => (options.client ?? client).post<PublicApiCreateListResponses, PublicApiCreateListErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/lists',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a list
 */
export const publicApiDeleteList = <ThrowOnError extends boolean = false>(options: Options<PublicApiDeleteListData, ThrowOnError>) => (options.client ?? client).delete<PublicApiDeleteListResponses, PublicApiDeleteListErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}',
    ...options
});

/**
 * Update a list
 */
export const publicApiUpdateList = <ThrowOnError extends boolean = false>(options: Options<PublicApiUpdateListData, ThrowOnError>) => (options.client ?? client).put<PublicApiUpdateListResponses, PublicApiUpdateListErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Subscribe to a list
 */
export const publicApiSubscribeToList = <ThrowOnError extends boolean = false>(options: Options<PublicApiSubscribeToListData, ThrowOnError>) => (options.client ?? client).post<PublicApiSubscribeToListResponses, PublicApiSubscribeToListErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}/subscribe',
    ...options
});

/**
 * Unsubscribe from a list
 */
export const publicApiUnsubscribeFromList = <ThrowOnError extends boolean = false>(options: Options<PublicApiUnsubscribeFromListData, ThrowOnError>) => (options.client ?? client).post<PublicApiUnsubscribeFromListResponses, PublicApiUnsubscribeFromListErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}/unsubscribe',
    ...options
});

/**
 * System Status
 */
export const systemSystemStatus = <ThrowOnError extends boolean = false>(options?: Options<SystemSystemStatusData, ThrowOnError>) => (options?.client ?? client).get<SystemSystemStatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });
