// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PublicApiGetAdminLogsData, PublicApiGetAdminLogsErrors, PublicApiGetAdminLogsResponses, PublicApiGetUserGroupsData, PublicApiGetUserGroupsErrors, PublicApiGetUserGroupsResponses, PublicApiLeaveGroupData, PublicApiLeaveGroupErrors, PublicApiLeaveGroupResponses, SystemSystemStatusData, SystemSystemStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get groups for the current user
 */
export const publicApiGetUserGroups = <ThrowOnError extends boolean = false>(options?: Options<PublicApiGetUserGroupsData, ThrowOnError>) => (options?.client ?? client).get<PublicApiGetUserGroupsResponses, PublicApiGetUserGroupsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups',
    ...options
});

/**
 * Leave a group
 */
export const publicApiLeaveGroup = <ThrowOnError extends boolean = false>(options: Options<PublicApiLeaveGroupData, ThrowOnError>) => (options.client ?? client).post<PublicApiLeaveGroupResponses, PublicApiLeaveGroupErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/groups/{group_id}/leave',
    ...options
});

/**
 * Get weekly logs (Admin only)
 */
export const publicApiGetAdminLogs = <ThrowOnError extends boolean = false>(options?: Options<PublicApiGetAdminLogsData, ThrowOnError>) => (options?.client ?? client).get<PublicApiGetAdminLogsResponses, PublicApiGetAdminLogsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/public/admin/logs',
    ...options
});

/**
 * System Status
 */
export const systemSystemStatus = <ThrowOnError extends boolean = false>(options?: Options<SystemSystemStatusData, ThrowOnError>) => (options?.client ?? client).get<SystemSystemStatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });
