// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_Public API-login_tma
 */
export type BodyPublicApiLoginTma = {
    /**
     * Init Data
     */
    init_data: string;
};

/**
 * GroupResponse
 */
export type GroupResponse = {
    /**
     * Telegram Id
     */
    telegram_id: number;
    /**
     * Group Name
     */
    group_name?: string | null;
    /**
     * Group Description
     */
    group_description?: string | null;
    /**
     * Group Username
     */
    group_username?: string | null;
    /**
     * Group Type
     */
    group_type?: string | null;
    /**
     * Group Members
     */
    group_members?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Is Group Admin
     */
    is_group_admin?: boolean;
    /**
     * Lists
     */
    lists?: Array<TagListWithSubscriptionResponse>;
};

/**
 * GroupSettingResponse
 */
export type GroupSettingResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * Auto Add New Members
     */
    auto_add_new_members?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Deleted At
     */
    deleted_at: string | null;
    /**
     * Active
     */
    active: boolean;
    /**
     * Auto Add Lists
     */
    auto_add_lists?: Array<TagListResponse>;
};

/**
 * GroupSettingUpdate
 */
export type GroupSettingUpdate = {
    /**
     * Auto Add New Members
     */
    auto_add_new_members?: boolean | null;
    /**
     * Auto Add List Ids
     */
    auto_add_list_ids?: Array<string> | null;
};

/**
 * GroupSummaryResponse
 */
export type GroupSummaryResponse = {
    /**
     * Telegram Id
     */
    telegram_id: number;
    /**
     * Group Name
     */
    group_name?: string | null;
    /**
     * Group Description
     */
    group_description?: string | null;
    /**
     * Group Username
     */
    group_username?: string | null;
    /**
     * Group Type
     */
    group_type?: string | null;
    /**
     * Group Members
     */
    group_members?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Active
     */
    active: boolean;
};

/**
 * GroupsResponse
 */
export type GroupsResponse = {
    /**
     * Items
     */
    items: Array<GroupSummaryResponse>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LogResponse
 */
export type LogResponse = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Group Id
     */
    group_id?: string | null;
    /**
     * Action
     */
    action?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LogsResponse
 */
export type LogsResponse = {
    /**
     * Items
     */
    items: Array<LogResponse>;
    /**
     * Count
     */
    count: number;
};

/**
 * TagListCreate
 */
export type TagListCreate = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Trigger Name
     */
    trigger_name: string;
    /**
     * Is System
     */
    is_system?: boolean;
    /**
     * Aliases
     */
    aliases?: Array<string>;
};

/**
 * TagListResponse
 */
export type TagListResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Trigger Name
     */
    trigger_name: string;
    /**
     * Is System
     */
    is_system?: boolean;
    /**
     * Aliases
     */
    aliases?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Active
     */
    active: boolean;
};

/**
 * TagListUpdate
 */
export type TagListUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Trigger Name
     */
    trigger_name?: string | null;
    /**
     * Aliases
     */
    aliases?: Array<string> | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * TagListWithSubscriptionResponse
 */
export type TagListWithSubscriptionResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Trigger Name
     */
    trigger_name: string;
    /**
     * Is System
     */
    is_system?: boolean;
    /**
     * Aliases
     */
    aliases?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Active
     */
    active: boolean;
    /**
     * Is Subscribed
     */
    is_subscribed: boolean;
};

/**
 * TagListsWithSubscriptionResponse
 */
export type TagListsWithSubscriptionResponse = {
    /**
     * Items
     */
    items: Array<TagListWithSubscriptionResponse>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type PublicApiGetGroupsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string | null;
        /**
         * Sort Desc
         */
        sort_desc?: boolean;
    };
    url: '/api/v1/public/groups';
};

export type PublicApiGetGroupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetGroupsError = PublicApiGetGroupsErrors[keyof PublicApiGetGroupsErrors];

export type PublicApiGetGroupsResponses = {
    /**
     * Successful Response
     */
    200: GroupsResponse;
};

export type PublicApiGetGroupsResponse = PublicApiGetGroupsResponses[keyof PublicApiGetGroupsResponses];

export type PublicApiGetGroupData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}';
};

export type PublicApiGetGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetGroupError = PublicApiGetGroupErrors[keyof PublicApiGetGroupErrors];

export type PublicApiGetGroupResponses = {
    /**
     * Successful Response
     */
    200: GroupResponse;
};

export type PublicApiGetGroupResponse = PublicApiGetGroupResponses[keyof PublicApiGetGroupResponses];

export type PublicApiGetGroupSettingsData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/settings';
};

export type PublicApiGetGroupSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetGroupSettingsError = PublicApiGetGroupSettingsErrors[keyof PublicApiGetGroupSettingsErrors];

export type PublicApiGetGroupSettingsResponses = {
    /**
     * Successful Response
     */
    200: GroupSettingResponse;
};

export type PublicApiGetGroupSettingsResponse = PublicApiGetGroupSettingsResponses[keyof PublicApiGetGroupSettingsResponses];

export type PublicApiUpdateGroupSettingsData = {
    body: GroupSettingUpdate;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/settings';
};

export type PublicApiUpdateGroupSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiUpdateGroupSettingsError = PublicApiUpdateGroupSettingsErrors[keyof PublicApiUpdateGroupSettingsErrors];

export type PublicApiUpdateGroupSettingsResponses = {
    /**
     * Successful Response
     */
    200: GroupSettingResponse;
};

export type PublicApiUpdateGroupSettingsResponse = PublicApiUpdateGroupSettingsResponses[keyof PublicApiUpdateGroupSettingsResponses];

export type PublicApiGetAdminLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string | null;
        /**
         * Sort Desc
         */
        sort_desc?: boolean;
    };
    url: '/api/v1/public/admin/logs';
};

export type PublicApiGetAdminLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetAdminLogsError = PublicApiGetAdminLogsErrors[keyof PublicApiGetAdminLogsErrors];

export type PublicApiGetAdminLogsResponses = {
    /**
     * Successful Response
     */
    200: LogsResponse;
};

export type PublicApiGetAdminLogsResponse = PublicApiGetAdminLogsResponses[keyof PublicApiGetAdminLogsResponses];

export type PublicApiLoginTmaData = {
    body: BodyPublicApiLoginTma;
    path?: never;
    query?: never;
    url: '/api/v1/public/auth/telegram-tma';
};

export type PublicApiLoginTmaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiLoginTmaError = PublicApiLoginTmaErrors[keyof PublicApiLoginTmaErrors];

export type PublicApiLoginTmaResponses = {
    /**
     * Response Public Api-Login Tma
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PublicApiLoginTmaResponse = PublicApiLoginTmaResponses[keyof PublicApiLoginTmaResponses];

export type PublicApiLoginTglData = {
    /**
     * Login Data
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/public/auth/telegram-tgl';
};

export type PublicApiLoginTglErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiLoginTglError = PublicApiLoginTglErrors[keyof PublicApiLoginTglErrors];

export type PublicApiLoginTglResponses = {
    /**
     * Response Public Api-Login Tgl
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PublicApiLoginTglResponse = PublicApiLoginTglResponses[keyof PublicApiLoginTglResponses];

export type PublicApiGetListsData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string | null;
        /**
         * Sort Desc
         */
        sort_desc?: boolean;
    };
    url: '/api/v1/public/groups/{group_id}/lists';
};

export type PublicApiGetListsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetListsError = PublicApiGetListsErrors[keyof PublicApiGetListsErrors];

export type PublicApiGetListsResponses = {
    /**
     * Successful Response
     */
    200: TagListsWithSubscriptionResponse;
};

export type PublicApiGetListsResponse = PublicApiGetListsResponses[keyof PublicApiGetListsResponses];

export type PublicApiCreateListData = {
    body: TagListCreate;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/lists';
};

export type PublicApiCreateListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiCreateListError = PublicApiCreateListErrors[keyof PublicApiCreateListErrors];

export type PublicApiCreateListResponses = {
    /**
     * Successful Response
     */
    200: TagListResponse;
};

export type PublicApiCreateListResponse = PublicApiCreateListResponses[keyof PublicApiCreateListResponses];

export type PublicApiDeleteListData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}';
};

export type PublicApiDeleteListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiDeleteListError = PublicApiDeleteListErrors[keyof PublicApiDeleteListErrors];

export type PublicApiDeleteListResponses = {
    /**
     * Response Public Api-Delete List
     *
     * Successful Response
     */
    200: string;
};

export type PublicApiDeleteListResponse = PublicApiDeleteListResponses[keyof PublicApiDeleteListResponses];

export type PublicApiUpdateListData = {
    body: TagListUpdate;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}';
};

export type PublicApiUpdateListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiUpdateListError = PublicApiUpdateListErrors[keyof PublicApiUpdateListErrors];

export type PublicApiUpdateListResponses = {
    /**
     * Successful Response
     */
    200: TagListResponse;
};

export type PublicApiUpdateListResponse = PublicApiUpdateListResponses[keyof PublicApiUpdateListResponses];

export type PublicApiClearListData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}/clear';
};

export type PublicApiClearListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiClearListError = PublicApiClearListErrors[keyof PublicApiClearListErrors];

export type PublicApiClearListResponses = {
    /**
     * Response Public Api-Clear List
     *
     * Successful Response
     */
    200: string;
};

export type PublicApiClearListResponse = PublicApiClearListResponses[keyof PublicApiClearListResponses];

export type PublicApiSubscribeToListData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}/subscribe';
};

export type PublicApiSubscribeToListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiSubscribeToListError = PublicApiSubscribeToListErrors[keyof PublicApiSubscribeToListErrors];

export type PublicApiSubscribeToListResponses = {
    /**
     * Response Public Api-Subscribe To List
     *
     * Successful Response
     */
    200: string;
};

export type PublicApiSubscribeToListResponse = PublicApiSubscribeToListResponses[keyof PublicApiSubscribeToListResponses];

export type PublicApiUnsubscribeFromListData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/lists/{list_id}/unsubscribe';
};

export type PublicApiUnsubscribeFromListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiUnsubscribeFromListError = PublicApiUnsubscribeFromListErrors[keyof PublicApiUnsubscribeFromListErrors];

export type PublicApiUnsubscribeFromListResponses = {
    /**
     * Response Public Api-Unsubscribe From List
     *
     * Successful Response
     */
    200: string;
};

export type PublicApiUnsubscribeFromListResponse = PublicApiUnsubscribeFromListResponses[keyof PublicApiUnsubscribeFromListResponses];

export type SystemSystemStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type SystemSystemStatusResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
