// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_Public API-login_tma
 */
export type BodyPublicApiLoginTma = {
    /**
     * Init Data
     */
    init_data: string;
};

/**
 * GenericResponse[LogsResponse]
 */
export type GenericResponseLogsResponse = {
    message: LogsResponse;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status Code
     */
    status_code: number;
};

/**
 * GenericResponse[dict]
 */
export type GenericResponseDict = {
    /**
     * Message
     */
    message: {
        [key: string]: unknown;
    };
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status Code
     */
    status_code: number;
};

/**
 * GroupResponse
 */
export type GroupResponse = {
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Group Name
     */
    group_name?: string | null;
    /**
     * Group Description
     */
    group_description?: string | null;
    /**
     * Group Username
     */
    group_username?: string | null;
    /**
     * Group Type
     */
    group_type?: string | null;
    /**
     * Group Members
     */
    group_members?: number | null;
    /**
     * Id
     */
    id: number;
};

/**
 * GroupsResponse
 */
export type GroupsResponse = {
    /**
     * Items
     */
    items: Array<GroupResponse>;
    /**
     * Count
     */
    count: number;
    /**
     * Isowner
     */
    isOwner?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LogResponse
 */
export type LogResponse = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Group Id
     */
    group_id?: string | null;
    /**
     * Action
     */
    action?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Datetime
     */
    datetime: string;
};

/**
 * LogsResponse
 */
export type LogsResponse = {
    /**
     * Items
     */
    items: Array<LogResponse>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type PublicApiGetUserGroupsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string | null;
        /**
         * Sort Desc
         */
        sort_desc?: boolean;
    };
    url: '/api/v1/public/groups';
};

export type PublicApiGetUserGroupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetUserGroupsError = PublicApiGetUserGroupsErrors[keyof PublicApiGetUserGroupsErrors];

export type PublicApiGetUserGroupsResponses = {
    /**
     * Successful Response
     */
    200: GroupsResponse;
};

export type PublicApiGetUserGroupsResponse = PublicApiGetUserGroupsResponses[keyof PublicApiGetUserGroupsResponses];

export type PublicApiLeaveGroupData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: number;
    };
    query?: never;
    url: '/api/v1/public/groups/{group_id}/leave';
};

export type PublicApiLeaveGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiLeaveGroupError = PublicApiLeaveGroupErrors[keyof PublicApiLeaveGroupErrors];

export type PublicApiLeaveGroupResponses = {
    /**
     * Successful Response
     */
    200: GenericResponseDict;
};

export type PublicApiLeaveGroupResponse = PublicApiLeaveGroupResponses[keyof PublicApiLeaveGroupResponses];

export type PublicApiGetAdminLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string | null;
        /**
         * Sort Desc
         */
        sort_desc?: boolean;
    };
    url: '/api/v1/public/admin/logs';
};

export type PublicApiGetAdminLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiGetAdminLogsError = PublicApiGetAdminLogsErrors[keyof PublicApiGetAdminLogsErrors];

export type PublicApiGetAdminLogsResponses = {
    /**
     * Successful Response
     */
    200: GenericResponseLogsResponse;
};

export type PublicApiGetAdminLogsResponse = PublicApiGetAdminLogsResponses[keyof PublicApiGetAdminLogsResponses];

export type PublicApiLoginTmaData = {
    body: BodyPublicApiLoginTma;
    path?: never;
    query?: never;
    url: '/api/v1/public/auth/telegram-tma';
};

export type PublicApiLoginTmaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiLoginTmaError = PublicApiLoginTmaErrors[keyof PublicApiLoginTmaErrors];

export type PublicApiLoginTmaResponses = {
    /**
     * Response Public Api-Login Tma
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PublicApiLoginTmaResponse = PublicApiLoginTmaResponses[keyof PublicApiLoginTmaResponses];

export type PublicApiLoginTglData = {
    /**
     * Login Data
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/public/auth/telegram-tgl';
};

export type PublicApiLoginTglErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicApiLoginTglError = PublicApiLoginTglErrors[keyof PublicApiLoginTglErrors];

export type PublicApiLoginTglResponses = {
    /**
     * Response Public Api-Login Tgl
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PublicApiLoginTglResponse = PublicApiLoginTglResponses[keyof PublicApiLoginTglResponses];

export type SystemSystemStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type SystemSystemStatusResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
